### ISSUE TITLE
Message d'erreur bizarre

### ISSUE THREAD

**Issue by Beltrando** [CocoaBob/PebbleTransilien#2]
Après réinstalaltion complète de la Pebble Steel:
1) Installation de "Paris Transilien"
2) Configuration du trajet : Juvisy - Versailles Chantiers; 
3) Clic Sélection: Affichage du premier train sur ce trajet: "CIME"
4) Clic Sélection: Affichage du détail du train (gares et horaires de passage): Ok
5) Clic Sélection sur n'importe quelle gare: Message d'erreur "Mémoire insuffisante"

On pensait qu'on allait pouvoir ici afficher les trains partant de cette gare, genre, pour prévoir une correspondance et partir ailleurs... 

Mais c'est peut être possible avec une autre montre que la Steel ?

**Comment by CocoaBob** [comment]
Hi,

I've developed the message especially for the original Pebble and Pebble Steel, because they have only 24KB of memory. Besides the size occupied by the app itself, we have only about 6-8KB memory left for running. Each window will cost about 1KB, so we can't open more than 2-3 windows, especially after the search window, because it's the most complex one, and it needs to load the data (about 8KB). On Pebble / Pebble Steel, I don't even load the data into memory but searching directly on the disk, so the searching is much slower than Pebble Time.

One workaround is adding your searching to the Favorites list, then return home and open the new favorite, so that we can avoid the searching window staying in the memory.

I've already optimized the app a lot, and removed some unimportant features for the 24KB memory devices, like Small Timetable, Automatic Text Scrolling, Relative Time, Quick Searching, to reduce the size of the app itself, so that we can have more free memory after launching.

I'm sorry about the limit.

**Comment by Beltrando** [comment]
Yeap. Merci pour ces optimisations!

 "One workaround is adding your searching to the Favorites list, then return home and open the new favorite, so that we can avoid the searching window staying in the memory.":  C'est ce que je fais systématiquement (je ne recherche que par les favoris). 

Maintenant, après avoir eu ce premier message d'erreur, j'ai deux nouveaux comportements bloquants. Cf. nouveaux tickets #3 et #4
